all: AvlTreeB.h BinarySearchTree1.h BinarySearchTree2.h dsexceptions.h TestAVLTree.cpp TestBinarySearchTree1.cpp TestBinarySearchTree2.cpp
	g++ -g -O2 TestAVLTree.cpp -o AVL
	g++ -g -O2 TestBinarySearchTree1.cpp -o BST1
	g++ -g -O2 TestBinarySearchTree2.cpp -o BST2
	
clean:
	rm AVL
	rm BST1
	rm BST2
 
